# This file was autogenerated using flake8.
pythinux.py:6:1: F401 'traceback' imported but unused
pythinux.py:15:1: F401 'asyncio' imported but unused
pythinux.py:25:1: E722 do not use bare 'except'
pythinux.py:28:80: E501 line too long (86 > 79 characters)
pythinux.py:53:80: E501 line too long (86 > 79 characters)
pythinux.py:310:80: E501 line too long (103 > 79 characters)
pythinux.py:396:80: E501 line too long (109 > 79 characters)
pythinux.py:404:80: E501 line too long (109 > 79 characters)
pythinux.py:690:80: E501 line too long (82 > 79 characters)
pythinux.py:692:80: E501 line too long (124 > 79 characters)
pythinux.py:954:5: E266 too many leading '#' for block comment
pythinux.py:958:5: E266 too many leading '#' for block comment
pythinux.py:976:5: E266 too many leading '#' for block comment
pythinux.py:1008:80: E501 line too long (99 > 79 characters)
pythinux.py:1009:80: E501 line too long (102 > 79 characters)
pythinux.py:1042:5: F841 local variable 'current_directory' is assigned to but never used
pythinux.py:1145:21: F601 dictionary key 'saveUserList' repeated with different values
pythinux.py:1152:21: F601 dictionary key 'saveUserList' repeated with different values
pythinux.py:1194:5: F841 local variable 'CURRDIR' is assigned to but never used
pythinux.py:1200:80: E501 line too long (80 > 79 characters)
pythinux.py:1348:5: F841 local variable 'current_directory' is assigned to but never used
pythinux.py:1451:9: F841 local variable 'x' is assigned to but never used
pythinux.py:1641:5: F841 local variable 'g' is assigned to but never used
